SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `gwat_template`;
CREATE TABLE `gwat_template` (
  `gwat_id` int(10) NOT NULL AUTO_INCREMENT,
  `job_id` double(10,0) DEFAULT NULL,
  `wait_time` double(10,0) DEFAULT NULL,
  `n_procs` double(10,0) DEFAULT NULL,
  `avg_cpu_time_used` double(10,0) DEFAULT NULL,
  `used_mem` double(10,0) DEFAULT NULL,
  `req_n_procs` double(10,0) DEFAULT NULL,
  `req_time` double(10,0) DEFAULT NULL,
  `req_memory` double(10,0) DEFAULT NULL,
  `status` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `user_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `group_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `executable_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `queue_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `partition_no` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `orig_site_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `last_run_site_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `job_str` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `job_str_param` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `used_network` double(10,0) DEFAULT NULL,
  `used_disk` double(10,0) DEFAULT NULL,
  `used_res` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `req_platform` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `req_network` double(10,0) DEFAULT NULL,
  `req_disk` double(10,0) DEFAULT NULL,
  `req_res` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `vvoid` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `proj_id` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `day_of_week` double(10,0) DEFAULT NULL,
  `week_no` double(10,0) DEFAULT NULL,
  `hour_of_day` double(10,0) DEFAULT NULL,
  `run_time` double(10,0) DEFAULT NULL,
  PRIMARY KEY (`gwat_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
